### ISSUE TITLE
需求

### ISSUE THREAD

**Issue by sorrycc** [dora-js/dora-util-is-async#1]
要实现一个 isAsync 的方法，能判断里面是否包含 this.callback，有返回 true，没有返回 false 。

``` javascript
isAsync(() => { 1; }) // false;
isAsync({} => { this.callback(); }) // true
isAsync({} => { setTimeout(() => this.callback, 1000); }) // true
isAsync({} => { that.callback(); }) // false
isAsync({} => { const that = this; setTimeout(() => { that.callback(err, 1); }, 1000); }) // true
```

**Comment by sorrycc** [comment]
@army8735 已搞完。。

**Comment by YuhangGe** [comment]
是只判断 this.callback() 还是判断有调用当前 context 的 callback ？比如 var me = this; me.callback()

**Comment by YuhangGe** [comment]
看测试用例只考虑了 this. 的情况。 这就要求用户必须用 => 函数来写了。感觉有些用户可能会采坑。

**Comment by army8735** [comment]
仔细看看先

**Comment by YuhangGe** [comment]
``` js
var c = (function () {this.callback(); }).bind(this); c();
```

js 是门很难猜透的语言。这个例子是故意找出来的，现实中不大可能这样写。所以我感觉还是靠谱的。

此外，似乎只能 Parse es5，我试了下箭头函数不支持。我们工具是用的 babel，但是否有可能写插件的同学不一定用 babel

**Comment by YuhangGe** [comment]
不过我故意找，也不是去看了源代码。只是直觉这种情况不好判断。现实中，js 确实是可能千奇百怪的写法。
